# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 臣子木
subtitle: 臣子木的学习、生活
description: 臣子木的博客 | web前端 | html | css | html5 | css3 | javascript | jquery | nodejs | angularjs
keywords: web前端 | html | css | html5 | css3 | javascript | jquery | nodejs | angularjs
author: chenzimu
email: sdlichen@gmail.com
language: zh-cn
timezone:
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://chenzimu.com
root: /
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: resume/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme:  cactus-dark

#avatar
avatar: /images/avatar.jpg

# Social links
social:
  github: https://github.com/chenzimu
  weibo: http://www.weibo.com/377800902

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github : git@github.com:muzichen/muzichen.github.io.git,master
  # branch: master

#SEO
sitemap:
    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xml

# duoshuo_shortname: chenzimu

# feed settings
feed:
  type: atom
  path: atom.xml
  limit: 20
